### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by sirkitree** [janusvr/janus-server#20]
This issue is to discuss a general approach for plugins. Here are my thoughts so far, and as they change through discussion I'll update this original post.

1. Plugins should be third party node modules which can be installed via npm.
1. Plugins are installed in a plugins directory and the server.js should auto detect them.
1. Possible have a list of enabled plugins in config.json (Re: #25)
1. Plugins should have a few standard functions exposed, like `init()`. Format and standards to be figured out in the future, but [this PR](https://github.com/janusvr/janus-server/pull/18) is a good start.

Note that we don't have to start out with this sort of thing, we could include a few standard ones I think and use them to work out the architecture, but I want to allow for others to be able to create their own plugins without needing to actually commit them to this repo.

**Comment by sirkitree** [comment]
The ircjsbot has some interesting plugin architecture: https://github.com/nlogax/ircjsbot

Basically there is a config.json with a plugins variable in which the user can specify which plugins to enable. Then there is a plugins directory which is another repo with a bunch of plugins included as a submodule. 

Not sure I like the idea of all plugins being in the same repo, but rather each one being it's own module so that anyone can create and maintain there own, but I could be persuaded if others thought this approach was viable.

**Comment by sirkitree** [comment]
Here's an excellent short presentation on some module patterns: http://darrenderidder.github.io/talks/ModulePatterns/#/

**Comment by timschwartz** [comment]
https://github.com/janusvr/janus-server/pull/35

**Comment by timschwartz** [comment]
Done.
