### ISSUE TITLE
Remove the current webserver

### ISSUE THREAD

**Issue by sirkitree** [janusvr/janus-server#22]
There is currently a webserver that runs on :8080 that basically broadcasts the server.log. I'd like to remove this as sometimes that file gets very large and hitting this url can actually bring down the server process.

**Comment by timschwartz** [comment]
What if we rotated the server.log when it gets to a certain size instead?

**Comment by sirkitree** [comment]
I currently have our server doing that on a nightly cron job, but it would be nice if the code here did something like that. Is there a reason to expose the server logs? Maybe @JamesMcCrae uses them when troubleshooting the client?

**Comment by timschwartz** [comment]
I think it would be nice for anyone running their own server, but it should probably at least be password protected.

**Comment by timschwartz** [comment]
We could make a plugin to log things to a database to replace the webserver.

**Comment by sirkitree** [comment]
Personally I'd rather have server logs in a file than a database, but I'm curious to hear what you think the advantages of doing so might be.

We already have a mysql db, so we could probably use that, and we currently are logging some stuff into one of those tables, but typically it's a good idea to keep logging in flat files in my experience.

**Comment by timschwartz** [comment]
Well, I mean in addition to the standard server.log. 

Some people might find it more convenient than having to ssh in to read the logs.

**Comment by sirkitree** [comment]
I wonder if @lisa-lionheart might chime in on the original reason she imcorporated the express server so we can make sure that we're not trampling on something whose history we don't understand.

**Comment by source83** [comment]
I've put in a flag for this, and it can be set in the config file now.

**Comment by bioid** [comment]
Since we've found a use for this webserver (exposing APIs like the party list and popular rooms) I'm going to close this issue.
