### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by sirkitree** [janusvr/janus-server#24]
We should specify the license for this software.

Current options being discussed mainly relate to the distribution of server plugins.

## [GPL 3.0](http://choosealicense.com/licenses/gpl-3.0/)
This would ensure that the server code is always open and free as well as any plugins created for it.

## [LGPL 2.1](http://choosealicense.com/licenses/lgpl-2.1/)
This would ensure that the server code is always open and free but plugins would not have to be free and/or open source.

**Comment by sirkitree** [comment]
I'd like to advocate GPL v3: http://choosealicense.com/licenses/gpl-3.0/

**Comment by sirkitree** [comment]
Pull Request in #30

**Comment by timschwartz** [comment]
Does the GPL3 allow you to write closed-source plugins?

**Comment by sirkitree** [comment]
I work with an open source activist who would know, I'll ask.

**Comment by sirkitree** [comment]
People could totally sell plugins that use this code, they would just be required to also provide the source code when they sell it (which they'd have to in this case anyway as it's not compiled code) and under the terms of the GPL.

But if people make the plugins, they are under no obligation to distribute the code to anyone else.

**Comment by timschwartz** [comment]
>People could totally sell plugins that use this code,

>under the terms of the GPL.

So theoretically, they might sell one copy which then gets redistributed for free?

Does GPL2 have that same restriction?

**Comment by sirkitree** [comment]
GPL2 works the same way, yes.

**Comment by sirkitree** [comment]
If we wanted to allow a world where there was some sort of market for buying plugins, we'd probably want to go with the [Apache](https://en.wikipedia.org/wiki/Apache_License) 1.1 License which does not require that derivative works be distributed using the same license.

I'm not entirely sure how I feel about that, as I'd personally rather foster a ecosystem of sharing openly rather than closed markets. But I could be persuaded. Perhaps we should ask on the JanusVR subreddit?

**Comment by sirkitree** [comment]
Another option pointed out to me by a friend who understands licensing better than is is the [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)

This part protects the core janus-server code.
> "This license is mainly applied to libraries. You may copy, distribute and modify the software provided that modifications are described and licensed inside the modified files and licensed for free under LGPL."

This part allows other libraries to not need this license.
>  "Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be."

**Comment by sirkitree** [comment]
I'm going to summarize this in the original post.

**Comment by timschwartz** [comment]
I'm in favor of LGPL 2.1, but if everyone else wants GPL 3.0 I won't object.

If a person or company absolutely needs to keep their code proprietary they can always reimplement the server themselves from the API.

**Comment by sirkitree** [comment]
Opened an issue on the subreddit here: http://www.reddit.com/r/janusVR/comments/3bnuqg/weigh_in_which_open_source_license_should_the/

**Comment by bnolan** [comment]
I'm in favour of MIT, let people do whatever they want to do with the code. Scene in under MIT.

**Comment by timschwartz** [comment]
James opinion:

    from JamesMcCrae[F] sent 10 minutes ago
    
    Haven't thought a lot about it. Perhaps MIT or LGPL. Whatever is liberal.

**Comment by sirkitree** [comment]
Good to know, thank you. I'll leave the decision up to @lisa-lionheart since it's her's originally.

**Comment by sirkitree** [comment]
Going with MIT
