### ISSUE TITLE
self-signed certs won't work with janus at the moment

### ISSUE THREAD

**Issue by source83** [janusvr/janus-server#29]
MultiPlayerManager::SocketConnected()  
"Socket Error: The certificate is self-signed, and untrusted"  
MultiPlayerManager::SocketDisconnected()  
MultiPlayerManager::DoSocketConnect() - tcpsocket trying "spyd.junkonet.org" 5567 ...  

This is the messages janus spits out.
More or less same problem as using self signed certs on a web server when trying to open the room within janus.

**Comment by lisa-lionheart** [comment]
This is not a issue with the server, if you need to use a self signed certificate you need to either.

1. Get James to bundle the certificate into JanusVR
2. Get James to provide an option to disable certificate verification.

Option 2 would basically eliminate any advantage of using SSL as anyone would be able to do a man in the middle attack

**Comment by source83** [comment]
Gah, sorry, of course, this isn't server side.. face->palm...
Wonder if James could implement something like the "add exception" option you'd get in a normal web browser.
