### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sirkitree** [janusvr/janus-server#34]
First thing to do is decide what should be tested. Then decide what we should use for a test runner. Then hook it up to travis ci to run on pull requests.
- [ ] decide what to test
- [x] decide what to use for writing tests - [tape](https://github.com/substack/tape)
- [ ] setup travis ci to run test on pull requests

**Comment by bnolan** [comment]
For tests I recommend [tape](https://github.com/substack/tape). I also like [semistandard](https://github.com/Flet/semistandard) as a linter to make sure that there are no unused / undeclared variables, etc - but that's a seperate issue.

**Comment by sirkitree** [comment]
Thanks I've never heard of tape. Do you knwo anything about karma? That's the one I've seen used most often. What is it you like about tape?

**Comment by bnolan** [comment]
Tape is really minimal and is used by mafintosh, maxogden, substack, feross and a whole bunch of other prolific package authors. It's worked great for scene.

**Comment by sirkitree** [comment]
++

**Comment by bioid** [comment]
Testing has been implemented with Mocha as the test runner and Travis CI for continuous integration
