### ISSUE TITLE
Usernames stuck in online users after disconnect

### ISSUE THREAD

**Issue by source83** [janusvr/janus-server#43]
I checked the sql server, the ip that my nick has in there, is mine. But I'm not connected with any client.
It was a rouge process that I killed a few hours ago, but it looks like the server doesn't register that it's not connected any longer.

**Comment by timschwartz** [comment]
Can you reproduce the problem?

Can you edit server.js and change the "socket.on('close'" function to look like this?

```
socket.on('close', function() {
        log.info(s.id + ' disconnected: ' + addr);
        delete s._server._userList[s.id];
        self._sessions.remove(s);
    });
```

**Comment by source83** [comment]
it's on babylon, I've stopped working on the server code

**Comment by timschwartz** [comment]
ok, whenever you get a change, update your package.json:

```
"janus-mysql-userlist": "^0.0.3",
```
then npm install

**Comment by source83** [comment]
it's on babylon, I've stopped working on the server code

**Comment by sirkitree** [comment]
Babylon is still running the old code. Babylon is the same as vrsites @timschwartz - so this bug is against the old code. I don't know when I'll have time to update it as i've a wedding this weekend and am focused on other areas at this time.

**Comment by source83** [comment]
I've started looking at the problem.
I added your code changes to a fork; timschwartz.
There is another issue on the server now that's pretty bad:
It's a tls error: "Error: This socket has been ended by the other party" and some more info is dumped to the log at a rate of 10 times a second at the moment.
I restarted the pm2 server to remove the log file (it was 5.3GB in size).

**Comment by timschwartz** [comment]
Are there any clues to what triggers that error message?

Can you post more of the log?

**Comment by source83** [comment]
ERR! 08:59:20 server.js:133 ::ffff:184.65.68.92
ERR! 08:59:20 server.js:134 Error: This socket has been ended by the other party
ERR! 08:59:20 server.js:134     at TLSSocket.writeAfterFIN [as write] (net.js:299:12)
ERR! 08:59:20 server.js:134     at Session.send (/root/source83-test/src/Session.js:45:18)
ERR! 08:59:20 server.js:134     at /root/source83-test/src/Room.js:31:11
ERR! 08:59:20 server.js:134     at Object.SetPrototype.each (/root/source83-test/node_modules/simplesets/lib/simplesets.js:142:6)
ERR! 08:59:20 server.js:134     at Room.emit (/root/source83-test/src/Room.js:24:20)
ERR! 08:59:20 server.js:134     at Session.move (/root/source83-test/src/Session.js:179:22)
ERR! 08:59:20 server.js:134     at Session.parseMessage (/root/source83-test/src/Session.js:95:43)
ERR! 08:59:20 server.js:134     at LineStream.emit (events.js:109:17)
ERR! 08:59:20 server.js:134     at readableAddChunk (_stream_readable.js:164:16)
ERR! 08:59:20 server.js:134     at LineStream.Readable.push (_stream_readable.js:128:10)
ERR! 08:59:20 server.js:134  Socket error:  { [Error: This socket has been ended by the other party] code: 'EPIPE' }

**Comment by source83** [comment]
The server log is back up to 4.2 gb since last deletion :((

**Comment by timschwartz** [comment]
Is it always the same IP address?

**Comment by source83** [comment]
It was, but I haven't seen the same error in a while

**Comment by source83** [comment]
Here are some less fatal error and info messages that might need some looking into later on:
--------------------
info 01:52:33 src/Session.js:75 data: {"method":"chat", "data":"change the "newmtl corpse1.jpg" in your mtl to "newmtl corpse1.tga""}
info 01:52:33 src/Session.js:76 payload: undefined
ERR! 01:52:33 src/Session.js:50 Client error (::ffff:77.10.186.73, CJay): Unable to parse last message
info 01:52:52 src/Session.js:75 data: {"method":"chat", "data":"and the "map_Kd corpse1.jpg" to "map_Kd corpse1.png""}
info 01:52:52 src/Session.js:76 payload: undefined
ERR! 01:52:52 src/Session.js:50 Client error (::ffff:77.10.186.73, CJay): Unable to parse last message
--------------------
info 01:32:51 src/Session.js:75 data: {"method":"move", "data":{"pos":"5.35634 -0.000999973 -2.19684","dir":"-0.139 -0.00874 -0.99","view_dir":"-0.
139 -0.00874 -0.99","up_dir":"-0.00122 1 -0.00865","head_pos":"0 0 0","avatar":"<FireBoxRoom><Assets><AssetObject id=^body^ src=^C:\Users\Ika\Deskt
op\rndsht\cat.obj^ mtl=^C:\Users\Ika\Desktop\rndsht\cat.mtl^ /><AssetObject id=^head^ src=^Null^ mtl=^Null^/></Assets><Room><Ghost id=^Long Johnson
^ js_id=^1^ pos=^34.571613 0.031828 3.363312^ xdir=^0.794 0.000 0.607^ zdir=^-0.607 0.000 0.794^ head_id=^head^ head_pos=^0.000000 0.750000 0.00000
0^ body_id=^body^ userid_pos=^0.000000 0.200000 0.250000^ /></Room></FireBoxRoom>","room_edit":"<AssetWebSurface id=^web1^ src=^http://motherless.c
om/^ width=^1280^ height=^768^ cpos=^215 255^ spos=^0 0^ />"}}
info 01:32:51 src/Session.js:76 payload: undefined
ERR! 01:32:51 src/Session.js:50 Client error (::ffff:188.168.35.23, Long Johnson): Unable to parse last message
info 01:32:51 server.js:128 Client disconnected: ::ffff:118.208.81.52
--------------------
info 23:01:05 src/Session.js:75 data: {"method":"portal", "data":{"url":"file:///D:\Media\images\best\mb", "pos":"1.02146 -0.000999985 3.52804", "fwd":"-0.709639 0 -0.682227"}}
info 23:01:05 src/Session.js:76 payload: undefined
ERR! 23:01:05 src/Session.js:50 Client error (::ffff:75.75.53.104, Iddig): Unable to parse last message

**Comment by timschwartz** [comment]
I don't think this has anything to do with the users online list?

**Comment by source83** [comment]
Crap, no, it's general messages from the log
