### ISSUE TITLE
Usernames stuck in "online users"

### ISSUE THREAD

**Issue by source83** [janusvr/janus-server#47]
If you look at the currently online users, there are 2 users that first of, stand out version wise.
The user names in question are:
TK (34.11) and JealousDenae446 (42.1)
I did a quick connect to the presence server with a debug bot I've got and could not see any traffic from ether of those user names.
Might I recommend some form of denied entry protocol to users that connect with a version number lower than a certain version from latest ?
Since there are JSON protocol changes in play, new home rooms that they can't find since they have the old room hard coded.
For TK (34.11) there has been 2 home room updates and a LARGE amount of changes in how janus works.
I would suggest some form of "access denied, outdated client" message to clients older than so and so many major version changes.
For example, current version is 46.8, if they connect with 44.7 or earlier, then they get the "access denied, outdated client" message or something like that as an error message in the same way you get other errors like duplicate usernames etc.

**Comment by timschwartz** [comment]
Is this still occurring?

**Comment by source83** [comment]
Now and then I still see some stuck users, but I can't remember if there are any there right now

**Comment by source83** [comment]
Well, yes, it's still an issue.
My username is stuck in the list right now.

**Comment by timschwartz** [comment]
Did someone restart the server? I don't see it now.

**Comment by source83** [comment]
I did

**Comment by source83** [comment]
Okay, there are still usernames stuck in the server, not even the visual ones (the web view) as far as I can tell.
Hence why Ausie and FireFoxG among others keep fighting for their usernames pretty often.
I can probably debug this with a few minor changes on the live server (need the client connects and disconnects).

**Comment by bioid** [comment]
I pushed a change a few weeks ago that seems to have resolved this. Closing.

**Comment by source83** [comment]
Okiday
