### ISSUE TITLE
Unsubscribe followed by subscribe does not work!

### ISSUE THREAD

**Issue by JamesMcCrae** [janusvr/janus-server#50]
An unsubscribe packet for a specific roomid causes messages not to be sent to client even after they have resubscribed.  My workaround in the janus client for a long while has been *not to send the packet to unsubscribe*, but this problem needs to solved at its root, which is the server code.

Here is a minimal example using telnet that demonstrates this problem (for both clients I used telnet babylon.vrsites.com 5566):

Client 1:

{"method":"logon","data":{"userId":"client1", "version":"23.4","roomId":"345678354764987457"}}
{"method":"subscribe", "data": { "roomId": "345678354764987457" }}
{"method":"chat", "data": "You are subscribed and can hear me"}
{"method":"chat", "data": "You are unsubscribed so cannot hear me"}
{"method":"chat", "data": "You are subscribed again, but cannot hear me! :("}

Client 2:

{"method":"logon","data":{"userId":"client2", "version":"23.4","roomId":"345678354764987457"}}
{"method":"subscribe", "data": { "roomId": "345678354764987457" }}
{"method":"unsubscribe", "data": { "roomId": "345678354764987457" }}
{"method":"subscribe", "data": { "roomId": "345678354764987457" }}

To set up, first send both the logon and first subscribe packets for each of client 1 and client 2.  Then:

(expected) Client 1 sends the first chat message that client 2 can hear "You are subscribed and can hear me"
(expected) Client 2 unsubscribes and client 1 sends a chat message that client 2 correctly does not hear "You are unsubscribed so cannot hear me"
(bug) Client 2 subscribes to the room again, and client 1 sends a chat message, but client 1 does NOT receive the message "You are subscribed again, but cannot hear me! :("

Only skimming through the code at this point, but as a starting point for debugging, line 224 of Session.js stands out, which reads:

        this._rooms.slice(i,1);

which doesn't do anything (the intention appears to be to remove the element of the rooms array at index i, in which case the function "splice" should be used instead of "slice").

**Comment by JamesMcCrae** [comment]
Changing "slice" to "splice" on line 224 of Session.js should fix this bug.

Also, can I be added as a collaborator? :)

**Comment by source83** [comment]
Could I also be added again ?

**Comment by source83** [comment]
Okay, I'll probably get killed for this but I've made the change in the sessions file on vrsites for now until a "official" change is made in the git repo.
Also restarted the presence server so it'd load the change.

**Comment by JamesMcCrae** [comment]
Thanks source.  Going to send an email to them soon - unfortunately *.dgp.toronto.edu (primary email account) has no electricity at the moment :)

**Comment by sirkitree** [comment]
@JamesMcCrae you have a pending invitation currently. You should be able to accept it from the organization page: https://github.com/janusvr

@source83 an invitation has been sent to you as well.

**Comment by sirkitree** [comment]
Pull request for this here for testing: https://github.com/janusvr/janus-server/pull/51

Is this working on the vrsites server?

**Comment by source83** [comment]
yes, I did it manually on the main server

**Comment by JamesMcCrae** [comment]
Fix merged, thanks all!
