### ISSUE TITLE
Log ports

### ISSUE THREAD

**Issue by sirkitree** [janusvr/janus-server#7]
I'm not sure yet where this would go, but I'm willing to do a pull request if someone would guide me before I figure it out.

It would be nice to have record of what port people are logging in on. We have 5566 and 5567 available but in trying to debug some stuff on 5567, it would be great is the server.log had some indication of the ports.

Current problem I'm trying to debug is that people don't seem to see each other if using 5567.

**Comment by hazardu5** [comment]
I've noticed this problem too. A good way to approach this would be to set up two computers with the JanusVR client and have them both connect to a local copy of the server running on a single machine on your network and then add logging in various places to find out where it's breaking. Currently in the logs you should see `User: X signed on` if the user successfully connects via `Session.logon()` in `Session.js`. If you add `log.info('User: ' + this.id + ' entered room');` to `Session.enter_room()` you should see if the user is actually entering the room. If you do this for the other methods in Session you'll be able to see which ones are working and which ones aren't. It could be also that the JanusVR client is rejecting the self-signed certificate and is failing to connect to the server altogether and is incorrectly reporting that it is 'connected' when the '/' key is pressed in the client.

**Comment by sirkitree** [comment]
Excellent, this is very helpful @hazardu5. Thank you.

**Comment by sirkitree** [comment]
The root of the problem can be found here: https://github.com/janusvr/janus-server/pull/26#issuecomment-116814168

Once that is fixed there is probably no need to do this.
