### ISSUE TITLE
Can not connect to my own server

### ISSUE THREAD

**Issue by MarcoSteinke** [janusvr/janus-server#71]
Hello,
I cloned both the janus-server and the janus-examples and tried to deploy the "showcase room" while running my own server.

When I start the janus-server as the setup guide tells me and then connect via the browser I get the following error on my server:

```
node server.js
15812 started
Socket Server listening on port: 5566
Socket Server listening on port: 5566
Client connected ::ffff:172.19.240.1 pid: 15812
data: ▬♥☺☻☺☺�♥♥$m]�↨�R`�▬       �Y�♠�B¶�9x=→��→L�↑L
 ��e��AZ
payload: undefined
Client error (::ffff:172.19.240.1, Unnamed): Unable to parse last message
data: �����<↔=H��↔�H∟dzB ZZ‼☺‼☻‼♥�+�/�,�0̨̩�‼�¶��/5☺☺���↨�☺☺
payload: undefined
Client error (::ffff:172.19.240.1, Unnamed): Unable to parse last message
data:
payload: undefined
Client error (::ffff:172.19.240.1, Unnamed): Unable to parse last message
::ffff:172.19.240.1
Socket error:  Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Session.send (C:\Users\mstei\Desktop\VR\server\janus-server\src\Session.js:55:22)
    at Session.clientError (C:\Users\mstei\Desktop\VR\server\janus-server\src\Session.js:60:10)
    at Session.parseMessage (C:\Users\mstei\Desktop\VR\server\janus-server\src\Session.js:92:21) {
  errno: 'ECONNABORTED',
  code: 'ECONNABORTED',
  syscall: 'write'
}
data:��↔↨↑
☻☺#♣♣☺
payload: undefined
Client error (::ffff:172.19.240.1, Unnamed): Unable to parse last message
data: ↕►♦♦♦☺♣♣♣♠♠☺↕3+)��☺↔ �
�h[��t%�v��4���Q�Rݛ*���/k&-☻☺☺+

payload: undefined
Client error (::ffff:172.19.240.1, Unnamed): Unable to parse last message
Client disconnected: ::ffff:172.19.240.1
Client connected ::ffff:172.19.240.1 pid: 15812
```

I tried to connect multiple times and the server crashes on each try.

The webVR looks the following:

```html
<html>
<head>
<title>Showcase room</title>
</head>
<body>
<FireBoxRoom>
<Assets>

#Walls roof and floor

<AssetObject id="Main" src="Walls_Roof_And_Floor.dae" />

#Voronoi abstract city mesh

<AssetObject id="VoronoiCity" src="Voronoi_city.dae" />

#Wall image mesh

<AssetObject id="Wall_Screens" src="PictureFrames.obj" />





#Wall Images/gifs
#use image_id="Wall_Images" on object Wall_Screens

<AssetImage id="Wall_Images" src="changeme.png" />

#Wall Websurface 
#Use websurface_id="Wall_Web" on Wall_Screens
#width and height dicate the screen resolution.

<AssetWebSurface id="Wall_Web" src="http://www.insert360webpagehere.com" width="2000" height="1000" />

#Wall Video/Webm 
#Use websurface_id="Wall_Video" on Wall_Screens

<AssetVideo id="Wall_Video" src="insertfilehere.mp4" auto_play="true" loop="true" />
</Assets>
<Room visible="false" pos="-4.6 0 4.6" xdir="-0.707109 0 -0.707105" ydir="0 1 0" zdir="0.707105 0 -0.707109" default_sounds="false" >

#This is the structure
<Object id="Main" cull_face="none" lighting="false" collision_id="Main" />

#This is the Voronoi City, Experiment by changing the asset object above with another support mesh format (.obj, .dae, .fbx, and .3ds supported)
<!--<Object id="VoronoiCity" cull_face="none" lighting="false" col="#ffdfb1" />-->


#This is the wall image mesh
#To change the media that is displayed, substitute image_id part for the other supported media formats in the asset section above.
<Object id="Wall_Screens" lighting="false" image_id="Wall_Images" />

</Room>
</FireBoxRoom>
<script src="https://web.janusvr.com/janusweb.js"></script>
<script>elation.janusweb.init({url: document.location.href, server: 'wss://172.19.240.1:5566'})</script>
</body>
</html>
```

Where the server value is my deployed server ip with port.

**Comment by jbaicoianu** [comment]
He @MarcoSteinke, looks like the problem here is that the web client is attempting to make an encrypted connection to an unencrypted port - since the client is hosted on https, due to browser security restrictions this means unencrypted connections will be rejected. You'll need to set your server up with an SSL certificate, which you can get from https://letsencrypt.org/. 

Unfortunately the fact that you're using a local network makes this difficult, so you can also do a self-signed certificate and add the certificate to your browser's certificate store manually.

Once you've got the certificate, make them available on your filesystem and you can point to the public and private certificate files in the server config.

**Comment by MarcoSteinke** [comment]
> He @MarcoSteinke, looks like the problem here is that the web client is attempting to make an encrypted connection to an unencrypted port - since the client is hosted on https, due to browser security restrictions this means unencrypted connections will be rejected. You'll need to set your server up with an SSL certificate, which you can get from https://letsencrypt.org/.
> 
> Unfortunately the fact that you're using a local network makes this difficult, so you can also do a self-signed certificate and add the certificate to your browser's certificate store manually.
> 
> Once you've got the certificate, make them available on your filesystem and you can point to the public and private certificate files in the server config.

Thank you for your reply and sorry for my late feedback.

I am thankful for the tips in your answer and will try to apply them. Thanks!

**Comment by jbaicoianu** [comment]
Marking this as closed, it seems to have been a port mismatch (secure websocket connection over the unsecure websocket port)
