### ISSUE TITLE
Presence server crashes on connect

### ISSUE THREAD

**Issue by ciber-space** [janusvr/janus-server#72]
I'm using the grid example, and trying to connect to my presence server. I've tried connecting with and without ssl, and it still crashes. I don't know anything about your source code, but is args[0] the IP address? Could my IPV6 be causing an issue? I don't know, sorry, just trying to provide some input.

Here is the console output:

```
8548 started
Socket Server listening on port: 5566
Socket Server listening on port: 5566
SSL Server listening on port: 5567
SSL Server listening on port: 5567
Client connected ::ffff:67.221.151.115 pid: 8548
node[8548]: ../src/node_http_parser_impl.h:428:static void node::{anonymous}::Parser::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[0]->IsInt32()' failed.
 1: 0x953b10 node::Abort() [node]
 2: 0x953b97  [node]
 3: 0x96e384  [node]
 4: 0xbbae9f  [node]
 5: 0xbbce62 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x33d0ae1cfc5d 
Aborted

```

**Comment by ciber-space** [comment]
I should mention I tried the server on 2 different ubuntu machines; same problem on both.

**Comment by x1911** [comment]
The same happened

**Comment by jbaicoianu** [comment]
Thanks, sorry it took so long to look into this, I'd also been running into crashes when trying to install new instances of the server but hadn't had any luck debugging it. I think you're right, it was indeed ipv6 related, and updating some dependencies fixed it.
